"""empty message

Revision ID: 1e6ef0be4f9f
Revises: eef3876a5e22
Create Date: 2025-01-29 19:35:03.439865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6ef0be4f9f'
down_revision = 'eef3876a5e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
