"""empty message

Revision ID: bb1e14ca0245
Revises: 8c9c2797b363
Create Date: 2025-02-15 13:14:29.697115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1e14ca0245'
down_revision = '8c9c2797b363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_constraint('Favorites_type_key', type_='unique')
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('People', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Films', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('Favorites_type_key', ['type'])

    # ### end Alembic commands ###
