"""empty message

Revision ID: eef3876a5e22
Revises: 
Create Date: 2025-01-29 19:34:53.228771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef3876a5e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Films',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('episode_id', sa.String(length=250), nullable=False),
    sa.Column('release_date', sa.String(length=250), nullable=False),
    sa.Column('director', sa.String(length=250), nullable=False),
    sa.Column('producer', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('title')
    )
    op.create_table('Planets',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('diameter', sa.String(length=250), nullable=False),
    sa.Column('gravity', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=250), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Favorites',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('external_ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('type', sa.Enum('Planet', 'People', 'Films', name='favoritetypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['Users.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('type')
    )
    op.create_table('People',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('species', sa.String(length=250), nullable=False),
    sa.Column('skin_color', sa.String(length=250), nullable=False),
    sa.Column('hair_color', sa.String(length=250), nullable=False),
    sa.Column('height', sa.String(length=250), nullable=False),
    sa.Column('homeworld', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homeworld'], ['Planets.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('People')
    op.drop_table('Favorites')
    op.drop_table('Users')
    op.drop_table('Planets')
    op.drop_table('Films')
    # ### end Alembic commands ###
